
[tcp_connection]
host = "192.168.1.100"
port = 502

[serial_connection]
port = 'COM3'
baudrate = 9600
parity = "E"
stopbits = 1
bytesize = 7
framer = "ASCII"

[address]

[address.read]
x = 1024
y = 1280

[address.write]
y0 = 1280
y1 = 1281
y2 = 1282
y3 = 1283
y4 = 1284
y5 = 1285
